import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bean_counter, BeanCounterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jLmkJrwesdz8F3cuqBdovUBuepPxf+/mFMrVNVTvlEauXlnfgg8ID9Ahievxvfcc",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :bean_counter, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :bean_counter, :github,
  app_id: System.get_env("GITHUB_APP_ID"),
  installation_id: System.get_env("GITHUB_INSTALLATION_ID"),
  private_key: System.get_env("GITHUB_PRIVATE_KEY"),
  access_token: System.get_env("GITHUB_ACCESS_TOKEN"),
  project_id: System.get_env("GITHUB_PROJECT_ID"),
  status_field_id: System.get_env("GITHUB_STATUS_FIELD_ID"),
  status_in_progress: System.get_env("GITHUB_STATUS_IN_PROGRESS"),
  status_in_review: System.get_env("GITHUB_STATUS_IN_REVIEW"),
  start_date_field_id: System.get_env("GITHUB_START_DATE_FIELD_ID"),
  end_date_field_id: System.get_env("GITHUB_END_DATE_FIELD_ID"),
  org: "AlmirTestOrg",
  repo: "optimajz_d_vorkflou"

config :neuron,
  url: "https://api.github.com/graphql"
